@startuml Class Diagram

class PRChecker
class PRBuildChecker
class PRAPIChecker
class ACRJiraIssue
class ACRJiraService
class ACRRepository
class PRInformation


PRChecker *- PRInformation
PRChecker *-- PRBuildChecker
PRChecker *-- PRAPIChecker

ACRJiraService *- ACRJiraIssue

PRAPIChecker --> ACRRepository
PRAPIChecker --> ACRJiraService
PRAPIChecker ..> ACRJiraIssue

@enduml